apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: backend-node
          image: 377152274560.dkr.ecr.eu-west-3.amazonaws.com/backend-node-app:1.0
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: infoline
spec:
  selector:
    app: backend-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
