name: CI-CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installer les dépendances frontend
        working-directory: ./frontend
        run: npm install

      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Scan sécurité du code (Semgrep)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Installer les dépendances backend
        working-directory: ./backend
        run: npm install

  build-and-push:
    runs-on: ubuntu-latest
    needs: quality-check

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer les credentials AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Connexion à Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image backend
        run: |
          docker build -t backend-node-app ./backend
          docker tag backend-node-app:latest 377152274560.dkr.ecr.eu-west-3.amazonaws.com/backend-node-app:latest

      - name: Push image backend
        run: |
          docker push 377152274560.dkr.ecr.eu-west-3.amazonaws.com/backend-node-app:latest

      - name: Build image frontend
        run: |
          docker build -t frontend-react-app ./frontend
          docker tag frontend-react-app:latest 377152274560.dkr.ecr.eu-west-3.amazonaws.com/frontend-react-app:latest

      - name: Push image frontend
        run: |
          docker push 377152274560.dkr.ecr.eu-west-3.amazonaws.com/frontend-react-app:latest

      - name: Mettre à jour kubeconfig pour EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Déployer sur Kubernetes
        run: |
          kubectl apply -f kubernetes/
